// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZarzadzanieUrlopami.Data;

#nullable disable

namespace ZarzadzanieUrlopami.Migrations
{
    [DbContext(typeof(UrlopyDbContext))]
    [Migration("20250426143359_PreReporting")]
    partial class PreReporting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.DniRobocze", b =>
                {
                    b.Property<int>("IdDnia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_dnia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDnia"));

                    b.Property<DateOnly?>("DataDnia")
                        .HasColumnType("date")
                        .HasColumnName("data_dnia");

                    b.Property<int?>("IdKierownika")
                        .HasColumnType("int")
                        .HasColumnName("id_kierownika");

                    b.HasKey("IdDnia")
                        .HasName("PK__Dni_robo__9DC8EE78B8C63145");

                    b.HasIndex("IdKierownika");

                    b.HasIndex(new[] { "DataDnia" }, "IX_DniRobocze_Dzien");

                    b.ToTable("Dni_robocze", (string)null);
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.DostepneUrlopyRoczne", b =>
                {
                    b.Property<int>("IdDostepnegoUrlopu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_dostepnego_urlopu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDostepnegoUrlopu"));

                    b.Property<int?>("IdPracownika")
                        .HasColumnType("int")
                        .HasColumnName("id_pracownika");

                    b.Property<int?>("IdTypuUrlopu")
                        .HasColumnType("int")
                        .HasColumnName("id_typu_urlopu");

                    b.Property<int?>("Ilosc")
                        .HasColumnType("int")
                        .HasColumnName("ilosc");

                    b.Property<int?>("Rok")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rok")
                        .HasDefaultValueSql("(datepart(year,getdate()))");

                    b.HasKey("IdDostepnegoUrlopu")
                        .HasName("PK__Dostepne__6A75A46107D59F28");

                    b.HasIndex("IdPracownika");

                    b.HasIndex("IdTypuUrlopu");

                    b.ToTable("Dostepne_Urlopy_Roczne", (string)null);
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.Pracownicy", b =>
                {
                    b.Property<int>("IdPracownika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pracownika");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPracownika"));

                    b.Property<string>("Adres")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("adres");

                    b.Property<DateOnly>("DataRozpoczecia")
                        .HasColumnType("date")
                        .HasColumnName("data_rozpoczecia");

                    b.Property<int?>("DzieciPonizej14")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("dzieci_ponizej_14");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("haslo");

                    b.Property<int>("IdRoli")
                        .HasColumnType("int")
                        .HasColumnName("id_roli");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("imie");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mail");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nazwisko");

                    b.Property<string>("Plec")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("plec")
                        .IsFixedLength();

                    b.Property<int?>("StazPracyWDniach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("staz_pracy_w_dniach");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("telefon");

                    b.Property<int?>("Wiek")
                        .HasColumnType("int")
                        .HasColumnName("wiek");

                    b.HasKey("IdPracownika")
                        .HasName("PK__Pracowni__5D8E25F273BAF34A");

                    b.HasIndex("IdRoli");

                    b.HasIndex(new[] { "Nazwisko" }, "IX_Pracownicy_Nazwisko");

                    b.HasIndex(new[] { "Mail" }, "UQ_Pracownicy_Mail")
                        .IsUnique();

                    b.HasIndex(new[] { "Telefon" }, "UQ_Pracownicy_Telefon")
                        .IsUnique();

                    b.ToTable("Pracownicy", null, t =>
                        {
                            t.HasTrigger("Dodaj_DostepneUrlopyRoczne_GdyDodaszPracownika");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.Role", b =>
                {
                    b.Property<int>("IdRoli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_roli");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoli"));

                    b.Property<string>("Nazwa")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nazwa");

                    b.HasKey("IdRoli")
                        .HasName("PK__Role__3D4847E12850301E");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.StatusUrlopu", b =>
                {
                    b.Property<int>("IdStatusu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_statusu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatusu"));

                    b.Property<int?>("IdTypuStatusu")
                        .HasColumnType("int")
                        .HasColumnName("id_typu_statusu");

                    b.Property<string>("Wyjaśnienie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("wyjaśnienie");

                    b.HasKey("IdStatusu")
                        .HasName("PK__Status_U__761651A744506549");

                    b.HasIndex("IdTypuStatusu");

                    b.ToTable("Status_Urlopu", (string)null);
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.TypyStatusow", b =>
                {
                    b.Property<int>("IdTypuStat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_typu_stat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTypuStat"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nazwa");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("opis");

                    b.HasKey("IdTypuStat")
                        .HasName("PK__Typy_Sta__5301E33B60099E9B");

                    b.HasIndex(new[] { "Nazwa" }, "IX_TypyStatusow_Nazwa");

                    b.HasIndex(new[] { "Nazwa" }, "UQ_TypyStatusow_Nazwa")
                        .IsUnique();

                    b.ToTable("Typy_Statusow", (string)null);
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.TypyUrlopow", b =>
                {
                    b.Property<int>("IdTypuUrlopu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_typu_urlopu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTypuUrlopu"));

                    b.Property<string>("Nazwa")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nazwa");

                    b.HasKey("IdTypuUrlopu")
                        .HasName("PK__Typy_Url__EC7B687853AF0A3D");

                    b.HasIndex(new[] { "Nazwa" }, "IX_TypyUrlopow_Nazwa");

                    b.HasIndex(new[] { "Nazwa" }, "UQ_TypyUrlopow_Nazwa")
                        .IsUnique()
                        .HasFilter("[nazwa] IS NOT NULL");

                    b.ToTable("Typy_Urlopow", (string)null);
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.TypyZwolnien", b =>
                {
                    b.Property<int>("IdTypuZwolnienia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_typu_zwolnienia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTypuZwolnienia"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nazwa");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("opis");

                    b.HasKey("IdTypuZwolnienia")
                        .HasName("PK__Typy_Zwo__57ED5384C9C8D8FC");

                    b.HasIndex(new[] { "Nazwa" }, "IX_TypyZwolnien_Nazwa");

                    b.HasIndex(new[] { "Nazwa" }, "UQ_Typy_Zwolnien_Nazwa")
                        .IsUnique();

                    b.ToTable("Typy_Zwolnien", (string)null);
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.Urlopy", b =>
                {
                    b.Property<int>("IdUrlopu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_urlopu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUrlopu"));

                    b.Property<DateOnly?>("DataKon")
                        .HasColumnType("date")
                        .HasColumnName("data_kon");

                    b.Property<DateOnly?>("DataPocz")
                        .HasColumnType("date")
                        .HasColumnName("data_pocz");

                    b.Property<int>("IdPracownika")
                        .HasColumnType("int")
                        .HasColumnName("id_pracownika");

                    b.Property<int>("IdStatusu")
                        .HasColumnType("int")
                        .HasColumnName("id_statusu");

                    b.Property<int>("IdTypuUrlopu")
                        .HasColumnType("int")
                        .HasColumnName("id_typu_urlopu");

                    b.HasKey("IdUrlopu")
                        .HasName("PK__Urlopy__DE8DBE5775C813AF");

                    b.HasIndex("IdPracownika");

                    b.HasIndex("IdStatusu");

                    b.HasIndex("IdTypuUrlopu");

                    b.ToTable("Urlopy", null, t =>
                        {
                            t.HasTrigger("UsunDni_PrzyOtrzymaniuUrlopow");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.WystawcyZwolnien", b =>
                {
                    b.Property<int>("IdWystawcy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_wystawcy");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWystawcy"));

                    b.Property<string>("Adres")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("adres");

                    b.Property<string>("Nazwa")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nazwa");

                    b.HasKey("IdWystawcy")
                        .HasName("PK__Wystawcy__27A7F6F0F0686277");

                    b.HasIndex(new[] { "Nazwa" }, "IX_WystawcyZwolnien_Nazwa");

                    b.HasIndex(new[] { "Nazwa" }, "UQ_WystawcyZwolnien_Nazwa")
                        .IsUnique()
                        .HasFilter("[nazwa] IS NOT NULL");

                    b.ToTable("Wystawcy_Zwolnien", (string)null);
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.Zastepstwa", b =>
                {
                    b.Property<int>("IdZastepstwa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_zastepstwa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZastepstwa"));

                    b.Property<int?>("IdPracownika")
                        .HasColumnType("int")
                        .HasColumnName("id_pracownika");

                    b.Property<int>("IdZmiany")
                        .HasColumnType("int")
                        .HasColumnName("id_zmiany");

                    b.HasKey("IdZastepstwa")
                        .HasName("PK__Zastepst__6C01E0AABCA220AD");

                    b.HasIndex("IdPracownika");

                    b.HasIndex("IdZmiany");

                    b.ToTable("Zastepstwa", (string)null);
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.Zmiany", b =>
                {
                    b.Property<int>("IdZmiany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_zmiany");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZmiany"));

                    b.Property<TimeOnly?>("GodzRozp")
                        .HasColumnType("time")
                        .HasColumnName("godz_rozp");

                    b.Property<TimeOnly?>("GodzZakon")
                        .HasColumnType("time")
                        .HasColumnName("godz_zakon");

                    b.Property<int>("IdDnia")
                        .HasColumnType("int")
                        .HasColumnName("id_dnia");

                    b.Property<int>("IdPracownika")
                        .HasColumnType("int")
                        .HasColumnName("id_pracownika");

                    b.HasKey("IdZmiany")
                        .HasName("PK__Zmiany__9B21969B31FEA3D7");

                    b.HasIndex("IdDnia");

                    b.HasIndex("IdPracownika");

                    b.ToTable("Zmiany", (string)null);
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.ZwolnieniaLekarskie", b =>
                {
                    b.Property<int>("IdZwolnienia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_zwolnienia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZwolnienia"));

                    b.Property<DateOnly?>("DataKon")
                        .HasColumnType("date")
                        .HasColumnName("data_kon");

                    b.Property<DateOnly?>("DataPocz")
                        .HasColumnType("date")
                        .HasColumnName("data_pocz");

                    b.Property<int>("IdPracownika")
                        .HasColumnType("int")
                        .HasColumnName("id_pracownika");

                    b.Property<int>("IdTypu")
                        .HasColumnType("int")
                        .HasColumnName("id_typu");

                    b.Property<int>("IdWystawcy")
                        .HasColumnType("int")
                        .HasColumnName("id_wystawcy");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("opis");

                    b.HasKey("IdZwolnienia")
                        .HasName("PK__Zwolnien__290A808EC69EAA28");

                    b.HasIndex("IdPracownika");

                    b.HasIndex("IdTypu");

                    b.HasIndex("IdWystawcy");

                    b.ToTable("Zwolnienia_Lekarskie", (string)null);
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.DniRobocze", b =>
                {
                    b.HasOne("ZarzadzanieUrlopami.Models.Pracownicy", "IdKierownikaNavigation")
                        .WithMany("DniRoboczes")
                        .HasForeignKey("IdKierownika")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_DniRobocze_Pracownicy");

                    b.Navigation("IdKierownikaNavigation");
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.DostepneUrlopyRoczne", b =>
                {
                    b.HasOne("ZarzadzanieUrlopami.Models.Pracownicy", "IdPracownikaNavigation")
                        .WithMany("DostepneUrlopyRocznes")
                        .HasForeignKey("IdPracownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_DostepneUrlopy_Pracownicy");

                    b.HasOne("ZarzadzanieUrlopami.Models.TypyUrlopow", "IdTypuUrlopuNavigation")
                        .WithMany("DostepneUrlopyRocznes")
                        .HasForeignKey("IdTypuUrlopu")
                        .HasConstraintName("FK_DostepneUrlopy_TypyUrlopow");

                    b.Navigation("IdPracownikaNavigation");

                    b.Navigation("IdTypuUrlopuNavigation");
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.Pracownicy", b =>
                {
                    b.HasOne("ZarzadzanieUrlopami.Models.Role", "IdRoliNavigation")
                        .WithMany("Pracownicies")
                        .HasForeignKey("IdRoli")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Pracownicy_Role");

                    b.Navigation("IdRoliNavigation");
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.StatusUrlopu", b =>
                {
                    b.HasOne("ZarzadzanieUrlopami.Models.TypyStatusow", "IdTypuStatusuNavigation")
                        .WithMany("StatusUrlopus")
                        .HasForeignKey("IdTypuStatusu")
                        .HasConstraintName("FK_StatusUrlopu_TypyStatusow");

                    b.Navigation("IdTypuStatusuNavigation");
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.Urlopy", b =>
                {
                    b.HasOne("ZarzadzanieUrlopami.Models.Pracownicy", "IdPracownikaNavigation")
                        .WithMany("Urlopies")
                        .HasForeignKey("IdPracownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Urlopy_Pracownicy");

                    b.HasOne("ZarzadzanieUrlopami.Models.StatusUrlopu", "IdStatusuNavigation")
                        .WithMany("Urlopies")
                        .HasForeignKey("IdStatusu")
                        .IsRequired()
                        .HasConstraintName("FK_Urlopy_Status_Urlopu");

                    b.HasOne("ZarzadzanieUrlopami.Models.TypyUrlopow", "IdTypuUrlopuNavigation")
                        .WithMany("Urlopies")
                        .HasForeignKey("IdTypuUrlopu")
                        .IsRequired()
                        .HasConstraintName("FK_Urlopy_TypyUrlopow");

                    b.Navigation("IdPracownikaNavigation");

                    b.Navigation("IdStatusuNavigation");

                    b.Navigation("IdTypuUrlopuNavigation");
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.Zastepstwa", b =>
                {
                    b.HasOne("ZarzadzanieUrlopami.Models.Pracownicy", "IdPracownikaNavigation")
                        .WithMany("Zastepstwas")
                        .HasForeignKey("IdPracownika")
                        .HasConstraintName("FK_Zastepstwa_Pracownicy");

                    b.HasOne("ZarzadzanieUrlopami.Models.Zmiany", "IdZmianyNavigation")
                        .WithMany("Zastepstwas")
                        .HasForeignKey("IdZmiany")
                        .IsRequired()
                        .HasConstraintName("FK_Zastepstwa_Zmiany");

                    b.Navigation("IdPracownikaNavigation");

                    b.Navigation("IdZmianyNavigation");
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.Zmiany", b =>
                {
                    b.HasOne("ZarzadzanieUrlopami.Models.DniRobocze", "IdDniaNavigation")
                        .WithMany("Zmianies")
                        .HasForeignKey("IdDnia")
                        .IsRequired()
                        .HasConstraintName("FK_Zmiany_DniRobocze");

                    b.HasOne("ZarzadzanieUrlopami.Models.Pracownicy", "IdPracownikaNavigation")
                        .WithMany("Zmianies")
                        .HasForeignKey("IdPracownika")
                        .IsRequired()
                        .HasConstraintName("FK_Zmiany_Pracownicy");

                    b.Navigation("IdDniaNavigation");

                    b.Navigation("IdPracownikaNavigation");
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.ZwolnieniaLekarskie", b =>
                {
                    b.HasOne("ZarzadzanieUrlopami.Models.Pracownicy", "IdPracownikaNavigation")
                        .WithMany("ZwolnieniaLekarskies")
                        .HasForeignKey("IdPracownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ZwolnieniaLekarskie_Pracownicy");

                    b.HasOne("ZarzadzanieUrlopami.Models.TypyZwolnien", "IdTypuNavigation")
                        .WithMany("ZwolnieniaLekarskies")
                        .HasForeignKey("IdTypu")
                        .IsRequired()
                        .HasConstraintName("FK_ZwolnieniaLekarskie_TypyZwolnien");

                    b.HasOne("ZarzadzanieUrlopami.Models.WystawcyZwolnien", "IdWystawcyNavigation")
                        .WithMany("ZwolnieniaLekarskies")
                        .HasForeignKey("IdWystawcy")
                        .IsRequired()
                        .HasConstraintName("FK_ZwolnieniaLekarskie_WystawcyZwolnien");

                    b.Navigation("IdPracownikaNavigation");

                    b.Navigation("IdTypuNavigation");

                    b.Navigation("IdWystawcyNavigation");
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.DniRobocze", b =>
                {
                    b.Navigation("Zmianies");
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.Pracownicy", b =>
                {
                    b.Navigation("DniRoboczes");

                    b.Navigation("DostepneUrlopyRocznes");

                    b.Navigation("Urlopies");

                    b.Navigation("Zastepstwas");

                    b.Navigation("Zmianies");

                    b.Navigation("ZwolnieniaLekarskies");
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.Role", b =>
                {
                    b.Navigation("Pracownicies");
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.StatusUrlopu", b =>
                {
                    b.Navigation("Urlopies");
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.TypyStatusow", b =>
                {
                    b.Navigation("StatusUrlopus");
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.TypyUrlopow", b =>
                {
                    b.Navigation("DostepneUrlopyRocznes");

                    b.Navigation("Urlopies");
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.TypyZwolnien", b =>
                {
                    b.Navigation("ZwolnieniaLekarskies");
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.WystawcyZwolnien", b =>
                {
                    b.Navigation("ZwolnieniaLekarskies");
                });

            modelBuilder.Entity("ZarzadzanieUrlopami.Models.Zmiany", b =>
                {
                    b.Navigation("Zastepstwas");
                });
#pragma warning restore 612, 618
        }
    }
}
